export const Message = {
  ALREADY_EXIST: 'User already exit.',
  REGISTERED_SUCCESSFULLY:'Congratulation! You are registered successfully..',
  MONGODB_CONNECTED:'MongoDB Connected.',
  USER_LOGGED_IN_SUCCESSFULLY:'User logged in successfully',
  USER_ALREADY_EXISTS:'User already exists.',
  REGISTRATION_ERROR:'Registration error',
  PASSWORD_MISMATCH:'password Mismatch',
  USER_NOT_FOUND:'User not found',
  INVALID_CREDENTIALS:'Invalid credentials',
  MONGODB_CONNECTION_ERROR:'MongoDB Connection Error',
  NO_TOKEN:'No token, authorization denied',
  TOKEN_ISnNOT_VALID:'Token is not valid',
  LISTENING_TO_PORT:'Listening to Port',
  INVALID_FILE_TYPE:'Invalid file type. Only JPG, JPEG, and PNG are allowed.',
  SERVER_ERROR:'Server Error',
  PROFILE_UPDATED_SUCCESSFULLY:'Profile updated successfully',
  PROFILE_FRTCHDES_SUCCESSFULLY:'Profile fetched successfully for user',
  NEW_PROFILE_CREATED_SUCCESSFULLY:'New profile created successfully for user',
};
