export const Message = {
  ALREADY_EXIST: 'User already exit.',
  REGISTERED_SUCCESSFULLY: 'Congratulation! You are registered successfully..',
  MONGODB_CONNECTED: 'MongoDB Connected.',
  USER_LOGGED_IN_SUCCESSFULLY: 'User logged in successfully',
  USER_ALREADY_EXISTS: 'User already exists.',
  REGISTRATION_ERROR: 'Registration error',
  PASSWORD_MISMATCH: 'password Mismatch',
  USER_NOT_FOUND: 'User not found',
  INVALID_CREDENTIALS: 'Invalid credentials',
  MONGODB_CONNECTION_ERROR: 'MongoDB Connection Error',
  NO_TOKEN: 'No token, authorization denied',
  TOKEN_ISnNOT_VALID: 'Token is not valid',
  LISTENING_TO_PORT: 'Listening to Port',
  INVALID_FILE_TYPE: 'Invalid file type. Only JPG, JPEG, and PNG are allowed.',
  SERVER_ERROR: 'Server Error',
  PROFILE_UPDATED_SUCCESSFULLY: 'Profile updated successfully',
  PROFILE_FRTCHDES_SUCCESSFULLY: 'Profile fetched successfully for user',
  NEW_PROFILE_CREATED_SUCCESSFULLY: 'New profile created successfully for user',
  MAIL_SENT: 'Mail sent successfully',
  OTP_MATCHED: 'Otp matched',
  OTP_NOT_MATCHED: 'Otp not matched',
  OPT_SEND: 'Otp sended successfuuly',
  PASS_UPDATED: 'Password updated successfully',
  PASS_NOT_MATCHED: 'Passwords do not match!',
  REGISTERED_SUCCESSFULLY:'Congratulation! You are registered successfully..',
  MONGODB_CONNECTED:'MongoDB Connected.',
  USER_LOGGED_IN_SUCCESSFULLY:'User logged in successfully',
  USER_ALREADY_EXISTS:'User already exists.',
  REGISTRATION_ERROR:'Registration error',
  PASSWORD_MISMATCH:'password Mismatch',
  USER_NOT_FOUND:'User not found',
  INVALID_CREDENTIALS:'Invalid credentials',
  MONGODB_CONNECTION_ERROR:'MongoDB Connection Error',
  NO_TOKEN:'No token, authorization denied',
  TOKEN_ISnNOT_VALID:'Token is not valid',
  LISTENING_TO_PORT:'Listening to Port',
  INVALID_FILE_TYPE:'Invalid file type. Only JPG, JPEG, and PNG are allowed.',
  SERVER_ERROR:'Server Error',
  PROFILE_UPDATED_SUCCESSFULLY:'Profile updated successfully',
  PROFILE_FRTCHDES_SUCCESSFULLY:'Profile fetched successfully for user',
  NEW_PROFILE_CREATED_SUCCESSFULLY:'New profile created successfully for user',
  OLD_PASSWORD_INCORRECT:'Old password is incorrecct.',
  PASSWORD_CHANGE_SUCCESSFULLY:'Password successfully changed.',
  ERROR_ADDING_AAPLICANT:'Error adding applicant',
  ERROR_RETRIEVING_APPLICANTS:'Error retrieving applicants',
  APPLICANT_SUBMIT_SUCCESSFULLY:'Applicant Submit Successfully',
  FETCHED_ALL_APPLICANTS:'Fetched all applicants successfully.',
  FETCHED_APPLICANT_SUCCESSFULLY:'Fetched applicant successfully',
  APPLICANT_NOT_FOUND:'Applicant Not Found.',
  UPDATED_SUCCESSFULLY:'Updated Successfully.',
  ERROR_UPDATING_APPLICANT:'Error updating applicant',
  APPLICANT_DELETED_SUCCESSFULLY:'Applicant deleted successfully',
  ERROR_DELETING_APPLICANT:'Error deleting applicant',
};
