const appConstants = Object.freeze({
  ACCESS_TOKEN_ERROR_CODE: 401,
  REFRESH_TOKEN_ERROR_CODE: 401,
  ACCESS_TOKEN: "accessToken",
  ACTION_TYPES: {
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    GET: "get",
    LIST: "list",
    LOGOUT: "logout",
  },
  noData: "-",
  dayEnums: {
    GoodMorning: "Good Morning",
    GoodAfternoon: "Good Afternoon",
    GoodEvening: "Good Evening",
  },
  handleScroll: {
    handleEditClick: () => {
      window.scrollTo({
        top: 0,
        behavior: "smooth",
      });
    },
  },
  handleResponse: {
    dataNotFound: "Sorry! No Result Found.",
    nullData: "---",
    somethingWrong: "Something went wrong.",
  },
  tableButtons: {
    Previous: "Previous",
    Next: "Next",
  },
  roleEnums: {
    Admin: "Admin",
    Vendor: "Vendor",
    Manager: "Manager",
    SuperAdmin: "Super Admin",
    Employee: "Employee",
  },
  searchPlaceHolder: "Search...",
  validationMessages: {
    required: (fieldName: string) =>
      `${
        fieldName.charAt(0).toUpperCase() + fieldName.slice(1).toLowerCase()
      } is required.`,
    format: (fieldName: string) => ` ${fieldName} should be in correct format.`,
    passwordLength: (fieldName: string, minLength: number) =>
      `${fieldName} must be at least ${minLength} characters.`,
    contactLength: (fieldName: string, minLength: number) =>
      `${fieldName} should be ${minLength} digit.`,
    passwordComplexity: (fieldName: string) =>
      `${fieldName} must be an uppercase lowercase number and special characters.`,
    passwordsMatch: (fieldName: string) => `${fieldName} must match.`,
    phoneNumber: (fieldName: string) =>
      `Invalid ${fieldName.toLowerCase()} format.`,
    notSameAsField: (fieldName: string, comparedField: string) =>
      `${fieldName} must be different from ${comparedField}.`,
    maxLength: (fieldName: string, maxLength: number | string) =>
      `${fieldName} must be at ${maxLength} characters.`,
    minLength: (fieldName: string, minLength: number | string) =>
      `${fieldName} must be at ${minLength} numbers.`,
    positiveNumber: (fieldName: string) => `${fieldName} must be positive`,
    greaterThan: (fieldName: string, parent: string) =>
      `${fieldName} must be greater than ${parent}`,
  },
  projectTitle: "Talent Box",
  passwordRegex:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$/,
  emailRegex: /^[^\s@]+@[^\s@]+\.[^\s@]{2,3}(?![^.\s])/,
  numberRegex: /^\d{10}$/,
  zipcodeRegex: /^\d{6}$/,
  positiveNumberRegex:
    /^[+]?([1-9][0-9]*(?:[.][0-9]*)?|0*\.0*[1-9][0-9]*)(?:[eE][+-][0-9]+)?$/,

  SUCCESS: true,
  ERROR: "Error",

  //Status Code
  NOT_FOUND: 404,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,

  ServiceEnums: {
    MasterService: "Master Item",
    UpdateService: "Update Master Item",
  },

  StockTypeEnums: {
    StockType: "Material Procurement",
    UpdateStock: "Update Material Procurement",
  },

  ButtonEnums: {
    Create: "Create Item",
    Submit: "Submit",
    Edit: "Edit",
    Updates: "Update",
    Cancel: "Cancel",
    ChangePassword: "Change Password",
  },

  Modules: {
    Login: "Login",
    Register: "Register",
    Applicant: "Applicant",
    Forgot: "Forgot",
    SKill: "Skill",
    Profile: "Profile",
    Dashboard: "Dashboard",
    Email: "Email",
    Reports: "Reports",
    EmailVerification: "Email Verification",
    UpdatePassword: "Update Password",
  },
  qualification: [
    { label: "Bachelors", value: "Bachelors" },
    { label: "Masters", value: "masters" },
    { label: "PhD", value: "phd" },
    { label: "Diploma", value: "diploma" },
    { label: "Associate Degree", value: "associate_degree" },
    { label: "Certification", value: "certification" },
    { label: "Doctorate", value: "doctorate" },
    { label: "Post Graduate Diploma", value: "post_graduate_diploma" },
    { label: "Advanced Diploma", value: "advanced_diploma" },
  ],
  passingYearType: [
    { label: "2005", value: 2005 },
    { label: "2006", value: 2006 },
    { label: "2007", value: 2007 },
    { label: "2008", value: 2008 },
    { label: "2009", value: 2009 },
    { label: "2010", value: 2010 },
    { label: "2011", value: 2011 },
    { label: "2012", value: 2012 },
    { label: "2013", value: 2013 },
    { label: "2014", value: 2014 },
    { label: "2015", value: 2015 },
    { label: "2016", value: 2016 },
    { label: "2017", value: 2017 },
    { label: "2018", value: 2018 },
    { label: "2019", value: 2019 },
    { label: "2020", value: 2020 },
    { label: "2021", value: 2021 },
    { label: "2022", value: 2022 },
    { label: "2023", value: 2023 },
    { label: "2024", value: 2024 },
    { label: "2025", value: 2025 },
    { label: "2026", value: 2026 },
    { label: "2027", value: 2027 },
    { label: "2028", value: 2028 },
    { label: "2029", value: 2029 },
  ],
  designationType: [
    { value: "SOFTWARE_ENGINEER", label: "Software Engineer" },
    { value: "FRONTED_DEVLOPER", label: "Frontend Developer" },
    { value: "BACKEND_DEVLOPER", label: "Backend Developer" },
    { value: "FULL_STACK_DEVLOPER", label: "Full Stack Developer" },
    { value: "DATA_ANALYST", label: "Data Analyst" },
    { value: "DATA_SCIENTIST", label: "Data Scientist" },
    { value: "PRODUCT_MANAGER", label: "Product Manager" },
    { value: "UI_UX", label: "UX/UI Designer" },
    { value: "QA", label: "QA Engineer" },
    { value: "DEVOPS", label: "DevOps Engineer" },
    { value: "BUSNESS_ANALYST", label: "Business Analyst" },
    { value: "TECHNICSL_SUPPORT", label: "Technical Support Engineer" },
  ],

  communicationOptions: [
    { value: "1", label: "1" },
    { value: "2", label: "2" },
    { value: "3", label: "3" },
    { value: "4", label: "4" },
    { value: "5", label: "5" },
    { value: "6", label: "6" },
    { value: "7", label: "7" },
    { value: "8", label: "8" },
    { value: "9", label: "9" },
    { value: "10", label: "10" },
  ],
  workPreferenceType: [
    { value: "remote", label: "Remote" },
    { value: "onsite", label: "Onsite" },
    { value: "hybrid", label: "Hybrid" },
  ],
  statusOptions: [
    { label: "Hold", value: "Hold" },
    { label: "Processing", value: "Processing" },
    { label: "Selected", value: "Selected" },
    { label: "Rejected", value: "Rejected" },
    { label: "Pending", value: "Pending" },
  ],

  interviewStageOptions: [
    { label: "1st Interview", value: "1st Interview" },
    { label: "2nd Interview", value: "2nd Interview" },
    { label: "HR", value: "HR" },
    { label: "Technical", value: "Technical" },
    { label: "Final", value: "Final" },
  ],
  experienceOptions: [
    { value: 0, label: "0 Years" },
    { value: 1, label: "1 Year" },
    { value: 2, label: "2 Years" },
    { value: 3, label: "3 Years" },
    { value: 4, label: "4 Years" },
    { value: 5, label: "5 Years" },
    { value: 6, label: "6 Years" },
    { value: 7, label: "7 Years" },
  ],
  gendersType: [
    { label: "Male", value: "male" },
    { label: "Female", value: "female" },
    { label: "Other", value: "other" },
  ],
  noticePeriodOptions: [
    { value: 0, label: "0 days" },
    { value: 15, label: "1-15 days" },
    { value: 30, label: "15 - 30 days" },
    { value: 45, label: "30 - 45 days" },
    { value: 60, label: "45 - 60 days" },
    { value: 70, label: "60+ days" },
  ],
  expectedPkgOptions: [
    { value: 0, label: "0-0.03" },
    { value: 10001, label: "10001-20000" },
    { value: 20001, label: "20001-30000" },
    { value: 30001, label: "30001-40000" },
    { value: 40001, label: "40001-50000" },
    { value: 50001, label: "Above 50000" },
  ],
  cityOptions: [
    { value: "Ahmedabad", label: "Ahemdabad" },
    { value: "Delhi", label: "Delhi" },
    { value: "Gandhi Nagar", label: "Gandhi Nagar" },
    { value: "Banglore", label: "Banglore" },
  ],
  skillOptions: [
    { value: "JavaScript", label: "JavaScript" },
    { value: "Node.js", label: "Node.js" },
    { value: "Python", label: "Python" },
    { value: "MongoDB", label: "MongoDB" },
    { value: "Java", label: "Java" },
    { value: "C", label: "C" },
    { value: "C++", label: "C++" },
    { value: "C#", label: "C#" },
    { value: "SQL", label: "SQL" },
    { value: "HTML", label: "HTML" },
    { value: "CSS", label: "CSS" },
    { value: "React", label: "React" },
    { value: "Angular", label: "Angular" },
    { value: "Vue.js", label: "Vue.js" },
    { value: "Ruby", label: "Ruby" },
    { value: "Ruby on Rails", label: "Ruby on Rails" },
    { value: "PHP", label: "PHP" },
    { value: "Swift", label: "Swift" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "Go", label: "Go" },
    { value: "R", label: "R" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "Django", label: "Django" },
    { value: "Flask", label: "Flask" },
    { value: "Laravel", label: "Laravel" },
    { value: "Spring Boot", label: "Spring Boot" },
    { value: "ASP.NET", label: "ASP.NET" },
    { value: "AWS", label: "AWS" },
    { value: "Azure", label: "Azure" },
    { value: "Google Cloud", label: "Google Cloud" },
    { value: "Docker", label: "Docker" },
    { value: "Kubernetes", label: "Kubernetes" },
    { value: "TensorFlow", label: "TensorFlow" },
    { value: "PyTorch", label: "PyTorch" },
    { value: "Machine Learning", label: "Machine Learning" },
    { value: "Deep Learning", label: "Deep Learning" },
    { value: "Data Science", label: "Data Science" },
    { value: "Blockchain", label: "Blockchain" },
    { value: "Git", label: "Git" },
    { value: "GitHub", label: "GitHub" },
    { value: "Jenkins", label: "Jenkins" },
    { value: "GraphQL", label: "GraphQL" },
    { value: "RESTful APIs", label: "RESTful APIs" },
    { value: "Firebase", label: "Firebase" },
    { value: "SQLite", label: "SQLite" },
    { value: "PostgreSQL", label: "PostgreSQL" },
    { value: "MySQL", label: "MySQL" },
    { value: "Redis", label: "Redis" },
    { value: "Elasticsearch", label: "Elasticsearch" },
    { value: "Apache Kafka", label: "Apache Kafka" },
    { value: "Apache Hadoop", label: "Apache Hadoop" },
    { value: "Unity", label: "Unity" },
    { value: "Unreal Engine", label: "Unreal Engine" },
    { value: "Arduino", label: "Arduino" },
    { value: "Raspberry Pi", label: "Raspberry Pi" },
    { value: "VMware", label: "VMware" },
    { value: "Linux", label: "Linux" },
    { value: "Shell Scripting", label: "Shell Scripting" },
    { value: "Data Structures", label: "Data Structures" },
    { value: "Algorithms", label: "Algorithms" },
    { value: "Operating Systems", label: "Operating Systems" },
    { value: "Computer Networks", label: "Computer Networks" },
    { value: "Artificial Intelligence", label: "Artificial Intelligence" },
    { value: "Cybersecurity", label: "Cybersecurity" },
    { value: "DevOps", label: "DevOps" },
    { value: "Agile", label: "Agile" },
    { value: "Scrum", label: "Scrum" },
    { value: "UI/UX Design", label: "UI/UX Design" },
    { value: "Design Patterns", label: "Design Patterns" },
    { value: "Test Automation", label: "Test Automation" },
    { value: "Manual Testing", label: "Manual Testing" },
    { value: "Business Intelligence", label: "Business Intelligence" },
    { value: "Tableau", label: "Tableau" },
    { value: "Power BI", label: "Power BI" },
  ],
  stateType: [
    { label: "Delhi", value: "delhi" },
    { label: "West Bengal", value: "west_bengal" },
    { label: "Tamil Nadu", value: "tamil_nadu" },
    { label: "Karnataka", value: "karnataka" },
    { label: "Telangana", value: "telangana" },
    { label: "Gujarat", value: "gujarat" },
    { label: "Maharashtra", value: "maharashtra" },
    { label: "Rajasthan", value: "rajasthan" },
    { label: "Uttar Pradesh", value: "uttar_pradesh" },
    { label: "Kerala", value: "kerala" },
    { label: "Chandigarh", value: "chandigarh" },
    { label: "Madhya Pradesh", value: "madhya_pradesh" },
    { label: "Bihar", value: "bihar" },
    { label: "Andhra Pradesh", value: "andhra_pradesh" },
    { label: "Odisha", value: "odisha" },
    { label: "Goa", value: "goa" },
    { label: "Jharkhand", value: "jharkhand" },
    { label: "Punjab", value: "punjab" },
    { label: "Assam", value: "assam" },
    { label: "Manipur", value: "manipur" },
    { label: "Sikkim", value: "sikkim" },
    { label: "Arunachal Pradesh", value: "arunachal_pradesh" },
    { label: "Nagaland", value: "nagaland" },
    { label: "Meghalaya", value: "meghalaya" },
    { label: "Karnataka", value: "karnataka" },
  ],
  countriesType :[{ label: "India", value: "india" }],
});

export default appConstants;
