const appConstants = Object.freeze({
  ACCESS_TOKEN_ERROR_CODE: 401,
  REFRESH_TOKEN_ERROR_CODE: 401,
  ACCESS_TOKEN: "accessToken",
  ACTION_TYPES: {
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    GET: "get",
    LIST: "list",
    LOGOUT: "logout",
  },
  noData: "-",
  dayEnums: {
    GoodMorning: "Good Morning",
    GoodAfternoon: "Good Afternoon",
    GoodEvening: "Good Evening",
  },
  handleScroll: {
    handleEditClick: () => {
      window.scrollTo({
        top: 0,
        behavior: "smooth",
      });
    },
  },
  handleResponse: {
    dataNotFound: "Sorry! No Result Found.",
    nullData: "---",
    somethingWrong: "Something went wrong.",
  },
  tableButtons: {
    Previous: "Previous",
    Next: "Next",
  },
  roleEnums: {
    Admin: "Admin",
    Vendor: "Vendor",
    Manager: "Manager",
    SuperAdmin: "Super Admin",
    Employee: "Employee",
  },
  searchPlaceHolder: "Search...",
  validationMessages: {
    required: (fieldName: string) =>
      `${
        fieldName.charAt(0).toUpperCase() + fieldName.slice(1).toLowerCase()
      } is required.`,
    format: (fieldName: string) => ` ${fieldName} should be in correct format.`,
    passwordLength: (fieldName: string, minLength: number) =>
      `${fieldName} must be at least ${minLength} characters.`,
    contactLength: (fieldName: string, minLength: number) =>
      `${fieldName} should be ${minLength} digit.`,
    passwordComplexity: (fieldName: string) =>
      `${fieldName} must be an uppercase lowercase number and special characters.`,
    passwordsMatch: (fieldName: string) => `${fieldName} must match.`,
    phoneNumber: (fieldName: string) =>
      `Invalid ${fieldName.toLowerCase()} format.`,
    notSameAsField: (fieldName: string, comparedField: string) =>
      `${fieldName} must be different from ${comparedField}.`,
    maxLength: (fieldName: string, maxLength: number | string) =>
      `${fieldName} must be at ${maxLength} characters.`,
    minLength: (fieldName: string, minLength: number | string) =>
      `${fieldName} must be at ${minLength} numbers.`,
    positiveNumber: (fieldName: string) => `${fieldName} must be positive`,
    greaterThan: (fieldName: string, parent: string) =>
      `${fieldName} must be greater than ${parent}`,
  },
  projectTitle: "Talent Box",
  passwordRegex:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$/,
  emailRegex: /^[^\s@]+@[^\s@]+\.[^\s@]{2,3}(?![^.\s])/,
  numberRegex: /^\d{10}$/,
  zipcodeRegex: /^\d{6}$/,
  positiveNumberRegex:
    /^[+]?([1-9][0-9]*(?:[.][0-9]*)?|0*\.0*[1-9][0-9]*)(?:[eE][+-][0-9]+)?$/,

  SUCCESS: true,
  ERROR: "Error",

  //Status Code
  NOT_FOUND: 404,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,

  ServiceEnums: {
    MasterService: "Master Item",
    UpdateService: "Update Master Item",
  },

  StockTypeEnums: {
    StockType: "Material Procurement",
    UpdateStock: "Update Material Procurement",
  },

  ButtonEnums: {
    Create: "Create Item",
    Submit: "Submit",
    Edit: "Edit",
    Updates: "Update",
    Cancel: "Cancel",
    ChangePassword: "Change Password",
  },

  Modules: {
    Login: "Login",
    Register: "Register",
    Applicant: "Applicant",
    Forgot: "Forgot",
    SKill: "Skill",
    Profile: "Profile",
    Dashboard: "Dashboard",
    Email: "Email",
    Reports: "Reports",
    EmailVerification: "Email Verification",
    UpdatePassword: "Update Password",
    Degree: "Degree",
  },
  qualification: [
    { label: "Bachelors", value: "Bachelors" },
    { label: "Masters", value: "masters" },
    { label: "Phd", value: "phd" },
    { label: "Diploma", value: "diploma" },
    { label: "Associate Degree", value: "associate_degree" },
    { label: "Certification", value: "certification" },
    { label: "Doctorate", value: "doctorate" },
    { label: "Post Graduate Diploma", value: "post_graduate_diploma" },
    { label: "Advanced Diploma", value: "advanced_diploma" },
  ],
  passingYearType: [
    { label: "2005", value: 2005 },
    { label: "2006", value: 2006 },
    { label: "2007", value: 2007 },
    { label: "2008", value: 2008 },
    { label: "2009", value: 2009 },
    { label: "2010", value: 2010 },
    { label: "2011", value: 2011 },
    { label: "2012", value: 2012 },
    { label: "2013", value: 2013 },
    { label: "2014", value: 2014 },
    { label: "2015", value: 2015 },
    { label: "2016", value: 2016 },
    { label: "2017", value: 2017 },
    { label: "2018", value: 2018 },
    { label: "2019", value: 2019 },
    { label: "2020", value: 2020 },
    { label: "2021", value: 2021 },
    { label: "2022", value: 2022 },
    { label: "2023", value: 2023 },
    { label: "2024", value: 2024 },
    { label: "2025", value: 2025 },
    { label: "2026", value: 2026 },
    { label: "2027", value: 2027 },
    { label: "2028", value: 2028 },
    { label: "2029", value: 2029 },
  ],

  designationType: [
    { value: "Software Engineer", label: "Software Engineer" },
    { value: "MERN Stack Developer", label: "MERN Stack Developer" },
    { value: "MEAN Stack Developer", label: "MEAN Stack Developer" },
    {
      value: "DotNet Full Stack Developer",
      label: ".NET Full Stack Developer",
    },
    { value: "Java Developer", label: "Java Developer" },
    { value: "Python Developer", label: "Python Developer" },
    { value: "PHP Developer", label: "Php Developer" },
    { value: "Frontend Developer", label: "Frontend Developer" },
    { value: "Backend Developer", label: "Backend Developer" },
    { value: "Full Stack Developer", label: "Full Stack Developer" },
    { value: "Data Analyst", label: "Data Analyst" },
    { value: "Data Scientist", label: "Data Scientist" },
    { value: "Product Manager", label: "Product Manager" },
    { value: "UX/UI Designer", label: "UX/UI Designer" },
    { value: "QA Engineer", label: "QA Engineer" },
    { value: "DevOps Engineer", label: "DevOps Engineer" },
    { value: "Business Analyst", label: "Business Analyst" },
    {
      value: "Technical Support Engineer",
      label: "Technical Support Engineer",
    },
    { value: "Other", label: "Other" },
    { value: "Na", label: "NA" },
  ],

  communicationOptions: [
    { value: "1", label: "1" },
    { value: "2", label: "2" },
    { value: "3", label: "3" },
    { value: "4", label: "4" },
    { value: "5", label: "5" },
    { value: "6", label: "6" },
    { value: "7", label: "7" },
    { value: "8", label: "8" },
    { value: "9", label: "9" },
    { value: "10", label: "10" },
  ],
  workPreferenceType: [
    { value: "remote", label: "Remote" },
    { value: "onsite", label: "Onsite" },
    { value: "hybrid", label: "Hybrid" },
  ],
  statusOptions: [
    { label: "Hold", value: "hold" },
    { label: "Processing", value: "in-process" },
    { label: "Selected", value: "selected" },
    { label: "Rejected", value: "rejected" },
    { label: "Pending", value: "pending" },
  ],

  interviewStageOptions: [
    { label: "First Interview Round", value: "first interview round" },
    { label: "Practical", value: "practical" },
    { label: "HR", value: "hr round" },
    { label: "Technical", value: "technical" },
    { label: "Client", value: "client" },
  ],
  experienceOptions: [
    { value: 0, label: "0 Years" },
    { value: 1, label: "1 Year" },
    { value: 2, label: "2 Years" },
    { value: 3, label: "3 Years" },
    { value: 4, label: "4 Years" },
    { value: 5, label: "5 Years" },
    { value: 6, label: "6 Years" },
    { value: 7, label: "7 Years" },
    { value: 8, label: "8 Years" },
    { value: 9, label: "9 Years" },
    { value: 10, label: "10 Years" },
    { value: 11, label: "11 Years" },
    { value: 12, label: "12 Years" },
  ],
  gendersType: [
    { label: "Male", value: "male" },
    { label: "Female", value: "female" },
    { label: "Other", value: "other" },
  ],
  maritalStatusType: [
    { label: "Single", value: "Single" },
    { label: "Married", value: "Married" },
  ],
  anyHandOnOffers: [
    { label: "Yes", value: true },
    { label: "No", value: false },
  ],

  noticePeriodOptions: [
    { value: "0", label: "Immediate" },
    { value: "1-10", label: "1-10 days" },
    { value: "9-20", label: "10 - 20 days" },
    { value: "19-30", label: "20 - 30 days" },
    { value: "29-40", label: "30 - 40 days" },
    { value: "39-100", label: "40+ days" },
  ],

  expectedPkgOptions: [
    { value: 0, label: "0" },
    { value: 0 - 1, label: "1 LPA" },
    { value: 1 - 2, label: "1-2 LPA" },
    { value: 2 - 3, label: "2 - 3 LPA" },
    { value: 3 - 4, label: "3 - 4 LPA" },
    { value: 4 - 5, label: "4 - 5 LPA" },
    { value: 5 - 7, label: "5 - 7  LPA" },
    { value: 7 - 10, label: "7 - 10 LPA" },
    { value: 10 - 15, label: "10 - 15 LPA" },
    { value: 15 - 20, label: "15 - 20 LPA" },
    { value: 20 - 30, label: "20 - 30 LPA" },
  ],
  cityOptions: [
    { value: "Ahmedabad", label: "Ahmedabad" },
    { value: "Delhi", label: "Delhi" },
    { value: "Gandhinagar", label: "Gandhinagar" },
    { value: "Bangalore", label: "Bangalore" },
    { value: "Mumbai", label: "Mumbai" },
    { value: "Chennai", label: "Chennai" },
    { value: "Kolkata", label: "Kolkata" },
    { value: "Hyderabad", label: "Hyderabad" },
    { value: "Pune", label: "Pune" },
    { value: "Jaipur", label: "Jaipur" },
    { value: "Lucknow", label: "Lucknow" },
    { value: "Indore", label: "Indore" },
    { value: "Surat", label: "Surat" },
    { value: "Chandigarh", label: "Chandigarh" },
    { value: "Bhopal", label: "Bhopal" },
    { value: "Patna", label: "Patna" },
    { value: "Nagpur", label: "Nagpur" },
    { value: "Vadodara", label: "Vadodara" },
    { value: "Coimbatore", label: "Coimbatore" },
    { value: "Visakhapatnam", label: "Visakhapatnam" },
    { value: "Kanpur", label: "Kanpur" },
    { value: "Nashik", label: "Nashik" },
    { value: "Agra", label: "Agra" },
    { value: "Thane", label: "Thane" },
    { value: "Madurai", label: "Madurai" },
    { value: "Mysore", label: "Mysore" },
    { value: "Bhubaneswar", label: "Bhubaneswar" },
    { value: "Kochi", label: "Kochi" },
    { value: "Vijayawada", label: "Vijayawada" },
    { value: "Guwahati", label: "Guwahati" },
    { value: "Shimla", label: "Shimla" },
    { value: "Ranchi", label: "Ranchi" },
    { value: "Udaipur", label: "Udaipur" },
    { value: "Rajkot", label: "Rajkot" },
    { value: "Dehradun", label: "Dehradun" },
    { value: "Trivandrum", label: "Trivandrum" },
    { value: "Dhanbad", label: "Dhanbad" },
    { value: "Faridabad", label: "Faridabad" },
    { value: "Meerut", label: "Meerut" },
    { value: "Siliguri", label: "Siliguri" },
    { value: "Gaya", label: "Gaya" },
  ],
  skillOptions: [
    { value: "JavaScript", label: "JavaScript" },
    { value: "Node.js", label: "Node.js" },
    { value: "Python", label: "Python" },
    { value: "MongoDB", label: "MongoDB" },
    { value: "Java", label: "Java" },
    { value: "C", label: "C" },
    { value: "C++", label: "C++" },
    { value: "C#", label: "C#" },
    { value: "SQL", label: "SQL" },
    { value: "HTML", label: "HTML" },
    { value: "CSS", label: "CSS" },
    { value: "React.js", label: "React.js" },
    { value: "Angular", label: "Angular" },
    { value: "Vue.js", label: "Vue.js" },
    { value: "Ruby", label: "Ruby" },
    { value: "Ruby on Rails", label: "Ruby on Rails" },
    { value: "PHP", label: "PHP" },
    { value: "Swift", label: "Swift" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "Go", label: "Go" },
    { value: "R", label: "R" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "Django", label: "Django" },
    { value: "Flask", label: "Flask" },
    { value: "Laravel", label: "Laravel" },
    { value: "Spring Boot", label: "Spring Boot" },
    { value: "ASP.NET", label: "ASP.NET" },
    { value: "AWS", label: "AWS" },
    { value: "Azure", label: "Azure" },
    { value: "Google Cloud", label: "Google Cloud" },
    { value: "Docker", label: "Docker" },
    { value: "Kubernetes", label: "Kubernetes" },
    { value: "TensorFlow", label: "TensorFlow" },
    { value: "PyTorch", label: "PyTorch" },
    { value: "Machine Learning", label: "Machine Learning" },
    { value: "Deep Learning", label: "Deep Learning" },
    { value: "Data Science", label: "Data Science" },
    { value: "Blockchain", label: "Blockchain" },
    { value: "Git", label: "Git" },
    { value: "GitHub", label: "GitHub" },
    { value: "Jenkins", label: "Jenkins" },
    { value: "GraphQL", label: "GraphQL" },
    { value: "RESTful APIs", label: "RESTful APIs" },
    { value: "Firebase", label: "Firebase" },
    { value: "SQLite", label: "SQLite" },
    { value: "PostgreSQL", label: "PostgreSQL" },
    { value: "MySQL", label: "MySQL" },
    { value: "Redis", label: "Redis" },
    { value: "Elasticsearch", label: "Elasticsearch" },
    { value: "Apache Kafka", label: "Apache Kafka" },
    { value: "Apache Hadoop", label: "Apache Hadoop" },
    { value: "Unity", label: "Unity" },
    { value: "Unreal Engine", label: "Unreal Engine" },
    { value: "Arduino", label: "Arduino" },
    { value: "Raspberry Pi", label: "Raspberry Pi" },
    { value: "VMware", label: "VMware" },
    { value: "Linux", label: "Linux" },
    { value: "Shell Scripting", label: "Shell Scripting" },
    { value: "Data Structures", label: "Data Structures" },
    { value: "Algorithms", label: "Algorithms" },
    { value: "Operating Systems", label: "Operating Systems" },
    { value: "Computer Networks", label: "Computer Networks" },
    { value: "Artificial Intelligence", label: "Artificial Intelligence" },
    { value: "Cybersecurity", label: "Cybersecurity" },
    { value: "DevOps", label: "DevOps" },
    { value: "Agile", label: "Agile" },
    { value: "Scrum", label: "Scrum" },
    { value: "UI/UX Design", label: "UI/UX Design" },
    { value: "Design Patterns", label: "Design Patterns" },
    { value: "Test Automation", label: "Test Automation" },
    { value: "Manual Testing", label: "Manual Testing" },
    { value: "Business Intelligence", label: "Business Intelligence" },
    { value: "Tableau", label: "Tableau" },
    { value: "Power BI", label: "Power BI" },
    { value: "Azure Data Factory", label: "Azure Data Factory" },
    { value: "Software Engineer", label: "Software Engineer" },
    { value: "Full Stack Developer", label: "Full Stack Developer" },
    { value: "JavaScript", label: "JavaScript" },
    { value: "jQuery", label: "jQuery" },
    { value: "HTML", label: "HTML" },
    { value: "AJAX", label: "AJAX" },
    { value: "ASP.Net", label: "ASP.Net" },
    { value: "ADO.Net", label: "ADO.Net" },
    { value: "Fiddler", label: "Fiddler" },
    { value: "Postman", label: "Postman" },
    { value: "Swagger", label: "Swagger" },
    { value: "Docker", label: "Docker" },
    { value: "Jenkins", label: "Jenkins" },
    { value: "Project Management", label: "Project Management" },
    { value: "Agile Methodology", label: "Agile Methodology" },
    { value: "Visual Studio", label: "Visual Studio" },
    { value: "Software Development", label: "Software Development" },
    { value: "web development", label: "web development" },
    { value: "Windows application", label: "Windows application" },
    { value: "javascript", label: "javascript" },
    { value: "Asp.Net Core", label: "Asp.Net Core" },
    { value: "MVC", label: "MVC" },
    { value: "Entity Framework", label: "Entity Framework" },
    { value: "SSIS Etl", label: "SSIS Etl" },
    { value: "Web Api", label: "Web Api" },
    { value: "JQuery", label: "JQuery" },
    { value: "CSS", label: "CSS" },
    { value: "React.js Library", label: "React.js Library" },
    { value: "Rabbitmq", label: "Rabbitmq" },
    { value: "Ms Sql Development", label: "Ms Sql Development" },
    { value: "SQL Development", label: "SQL Development" },
    { value: "Unit Testing", label: "Unit Testing" },
    { value: "C#", label: "C#" },
    { value: "Mvc", label: "Mvc" },
    { value: "Sql", label: "Sql" },
    { value: "Ajax", label: "Ajax" },
    { value: "Oop", label: "Oop" },
    { value: "MySQL", label: "MySQL" },
    { value: "Dotnet Web Application", label: "Dotnet Web Application" },
    { value: "Dotnet Development", label: "Dotnet Development" },
    { value: "ADO.NET", label: "ADO.NET" },
    { value: "LINQ", label: "LINQ" },
    { value: "C++", label: "C++" },
    { value: "DBMS", label: "DBMS" },
    { value: "Python", label: "Python" },
    { value: "Java", label: "Java" },
    { value: "C", label: "C" },
    { value: "Bootstrap", label: "Bootstrap" },
    { value: "GIT", label: "GIT" },
    { value: "Azure Key Vault", label: "Azure Key Vault" },
    { value: "Azure Functions", label: "Azure Functions" },
    { value: "Azure Blob", label: "Azure Blob" },
    { value: "SSRS", label: "SSRS" },
    { value: "XML", label: "XML" },
    { value: "Ajax Tools", label: "Ajax Tools" },
    { value: "Telerik Rad Control", label: "Telerik Rad Control" },
    { value: "CSL", label: "CSL" },
    { value: "Oracle Netsuite", label: "Oracle Netsuite" },
    { value: "Quick Books", label: "Quick Books" },
    { value: ".Net Core", label: ".Net Core" },
    { value: "Azure Fundamental", label: "Azure Fundamental" },
    { value: "Web Services", label: "Web Services" },
    { value: "Window Service", label: "Window Service" },
    { value: "Devops", label: "Devops" },
    { value: "Typing", label: "Typing" },
    { value: "MS Office", label: "MS Office" },
    { value: "Shorthand", label: "Shorthand" },
    { value: "ASP.Net MVC", label: "ASP.Net MVC" },
    { value: "ASP.Net Ajax", label: "ASP.Net Ajax" },
    { value: "Asp.Net Web Api", label: "Asp.Net Web Api" },
    { value: "Software Testing", label: "Software Testing" },
    { value: "Sales and Marketing", label: "Sales and Marketing" },
    { value: "Business Studies", label: "Business Studies" },
  ],
  stateType: [
    { label: "Delhi", value: "delhi" },
    { label: "West Bengal", value: "west_bengal" },
    { label: "Tamil Nadu", value: "tamil_nadu" },
    { label: "Karnataka", value: "karnataka" },
    { label: "Telangana", value: "telangana" },
    { label: "Gujarat", value: "gujarat" },
    { label: "Maharashtra", value: "maharashtra" },
    { label: "Rajasthan", value: "rajasthan" },
    { label: "Uttar Pradesh", value: "uttar_pradesh" },
    { label: "Kerala", value: "kerala" },
    { label: "Chandigarh", value: "chandigarh" },
    { label: "Madhya Pradesh", value: "madhya_pradesh" },
    { label: "Bihar", value: "bihar" },
    { label: "Andhra Pradesh", value: "andhra_pradesh" },
    { label: "Odisha", value: "odisha" },
    { label: "Goa", value: "goa" },
    { label: "Jharkhand", value: "jharkhand" },
    { label: "Punjab", value: "punjab" },
    { label: "Assam", value: "assam" },
    { label: "Manipur", value: "manipur" },
    { label: "Sikkim", value: "sikkim" },
    { label: "Arunachal Pradesh", value: "arunachal_pradesh" },
    { label: "Nagaland", value: "nagaland" },
    { label: "Meghalaya", value: "meghalaya" },
    { label: "Karnataka", value: "karnataka" },
  ],
  countriesType: [{ label: "India", value: "india" }],

  addedByOptions : [
    { label: "Resume", value: "Resume" },
    { label: "Manual", value: "Manual" },
    { label: "CSV", value: "Csv" },
  ],
});

export default appConstants;
